In [1]:
import pandas as pd

In [2]:
df_data = pd.read_csv(filepath_or_buffer='survey_results_public.csv', low_memory=False)
df_description = pd.read_csv(filepath_or_buffer='survey_results_schema.csv')

print (df_data.shape)
print(df_data.head())

(49191, 172)
   ResponseId                      MainBranch              Age  \
0           1  I am a developer by profession  25-34 years old
1           2  I am a developer by profession  25-34 years old
2           3  I am a developer by profession  35-44 years old
3           4  I am a developer by profession  35-44 years old
4           5  I am a developer by profession  35-44 years old

                                           EdLevel  \
0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
1              Associate degree (A.A., A.S., etc.)
2     Bachelor’s degree (B.A., B.S., B.Eng., etc.)
3     Bachelor’s degree (B.A., B.S., B.Eng., etc.)
4  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)

                                          Employment  \
0                                           Employed
1                                           Employed
2  Independent contractor, freelancer, or self-em...
3                                           Employed
4  Independent contractor, freelancer, or self-em...

                                    EmploymentAddl  WorkExp  \
0  Caring for dependents (children, elderly, etc.)      8.0
1                                              NaN      2.0
2                                None of the above     10.0
3                                None of the above      4.0
4  Caring for dependents (children, elderly, etc.)     21.0

                                     LearnCodeChoose  \
0  Yes, I am not new to coding but am learning ne...
1  Yes, I am not new to coding but am learning ne...
2  Yes, I am not new to coding but am learning ne...
3  Yes, I am not new to coding but am learning ne...
4  No, I am not new to coding and did not learn n...

                                           LearnCode  \
0  Online Courses or Certification (includes all ...
1  Online Courses or Certification (includes all ...
2  Online Courses or Certification (includes all ...
3  Other online resources (e.g. standard search, ...
4                                                NaN

                                         LearnCodeAI  ...  \
0  Yes, I learned how to use AI-enabled tools for...  ...
1  Yes, I learned how to use AI-enabled tools for...  ...
2  Yes, I learned how to use AI-enabled tools for...  ...
3  Yes, I learned how to use AI-enabled tools for...  ...
4  Yes, I learned how to use AI-enabled tools for...  ...

  AIAgentOrchestration  AIAgentOrchWrite AIAgentObserveSecure AIAgentObsWrite  \
0            Vertex AI               NaN                  NaN             NaN
1                  NaN               NaN                  NaN             NaN
2                  NaN               NaN                  NaN             NaN
3                  NaN               NaN                  NaN             NaN
4                  NaN               NaN                  NaN             NaN

                                    AIAgentExternal AIAgentExtWrite  \
0                                           ChatGPT             NaN
1                                               NaN             NaN
2  ChatGPT;Claude Code;GitHub Copilot;Google Gemini             NaN
3                               ChatGPT;Claude Code             NaN
4                                               NaN             NaN

                                             AIHuman  \
0                    When I don’t trust AI’s answers
1  When I don’t trust AI’s answers;When I want to...
2  When I don’t trust AI’s answers;When I want to...
3  When I don’t trust AI’s answers;When I want to...
4                    When I don’t trust AI’s answers

                                              AIOpen  ConvertedCompYearly  \
0              Troubleshooting, profiling, debugging              61256.0
1                          All skills. AI is a flop.             104413.0
2  Understand how things actually work, problem s...              53061.0
3                                                NaN              36197.0
4  critical thinking, the skill to define the tas...              60000.0

   JobSat
0    10.0
1     9.0
2     8.0
3     6.0
4     7.0

[5 rows x 172 columns]

### Завдання 1. Підрахунок загальної кількості респондентів

In [3]:
responents = df_data['ResponseId'].nunique() #кількість унікальних значень
print ('Загальна кількість респондентів в опитуванні: ', responents)

Загальна кількість респондентів в опитуванні:  49191

### Завдання 2. Аналіз повноти відповідей респондентів

In [4]:
print(df_description['qname']) #список питань
questions = list (set(df_description['qname']).intersection(df_data.columns))
#set(df_description['qname']) - set(df_data.columns) #питання зі списку у файлі опису, які відсутні у файлі результатів
df_data_cleared = df_data[questions].dropna(axis=0, inplace=False) #підрахунок результатів без пропусків

print ('Кількість респондентів, які відповіли на всі запитання з опитування: ', df_data_cleared.shape[0])

0        TechEndorse_1
1        TechEndorse_2
2        TechEndorse_3
3        TechEndorse_4
4        TechEndorse_5
            ...
134    AIAgentObsWrite
135    AIAgentExternal
136    AIAgentExtWrite
137            AIHuman
138             AIOpen
Name: qname, Length: 139, dtype: str
Кількість респондентів, які відповіли на всі запитання з опитування:  0

### Завдання 3. Статистичний аналіз досвіду респондентів

In [5]:
df_data.WorkExp.describe() #для перевірки

count    42893.000000
mean        13.367403
std         10.800117
min          1.000000
25%          5.000000
50%         10.000000
75%         20.000000
max        100.000000
Name: WorkExp, dtype: float64

In [6]:
pd.DataFrame([{
    'mean': round(df_data['WorkExp'].mean(), 2),
    'median': df_data['WorkExp'].median(),
    'mode': df_data['WorkExp'].mode()[0]
}])

    mean  median  mode
0  13.37    10.0  10.0

### Завдання 4. Аналіз віддаленої роботи

In [7]:
print(df_data.columns[df_data.apply(lambda col: col.astype(str).str.contains('remote', case=False, na=False)).any()]) #пошук колонки з форматом роботи
df_data['RemoteWork'].unique() #перевірка правильності написання варіантів

Index(['RemoteWork', 'TechOppose_15_TEXT', 'JobSatPoints_15_TEXT',
       'DatabaseHaveEntry', 'AIExplain', 'AIOpen'],
      dtype='str')

<StringArray>
[                                                                      'Remote',
                          'Hybrid (some in-person, leans heavy to flexibility)',
                                                                            nan,
                                                                    'In-person',
                               'Hybrid (some remote, leans heavy to in-person)',
 'Your choice (very flexible, you can come in when you want or just as needed)']
Length: 6, dtype: str

In [8]:
df_data_remote = df_data[df_data['RemoteWork']=='Remote']
print(df_data_remote)
print ('Кількість респондентів, які працюють віддалено: ' ,df_data_remote['ResponseId'].nunique() )

       ResponseId                      MainBranch              Age  \
0               1  I am a developer by profession  25-34 years old
3               4  I am a developer by profession  35-44 years old
7               8  I am a developer by profession  35-44 years old
8               9  I am a developer by profession  25-34 years old
9              10  I am a developer by profession  25-34 years old
...           ...                             ...              ...
49137       49138  I am a developer by profession  25-34 years old
49149       49150  I am a developer by profession  25-34 years old
49175       49176  I am a developer by profession  25-34 years old
49179       49180  I am a developer by profession  25-34 years old
49180       49181  I am a developer by profession  18-24 years old

                                                 EdLevel Employment  \
0        Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   Employed
3           Bachelor’s degree (B.A., B.S., B.Eng., etc.)   Employed
7         Professional degree (JD, MD, Ph.D, Ed.D, etc.)   Employed
8           Bachelor’s degree (B.A., B.S., B.Eng., etc.)   Employed
9        Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   Employed
...                                                  ...        ...
49137       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   Employed
49149    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   Employed
49175    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   Employed
49179                Associate degree (A.A., A.S., etc.)   Employed
49180  Secondary school (e.g. American high school, G...    Student

                                          EmploymentAddl  WorkExp  \
0        Caring for dependents (children, elderly, etc.)      8.0
3                                      None of the above      4.0
7      Engaged in paid work (20-29 hours per week);Tr...     22.0
8      Caring for dependents (children, elderly, etc....      9.0
9                                      None of the above      7.0
...                                                  ...      ...
49137                                  None of the above      8.0
49149  Engaged in paid work (less than 10 hours per w...     10.0
49175                                                NaN      4.0
49179                       Attending school (part-time)      5.0
49180        Engaged in paid work (20-29 hours per week)      1.0

                                         LearnCodeChoose  \
0      Yes, I am not new to coding but am learning ne...
3      Yes, I am not new to coding but am learning ne...
7      Yes, I am not new to coding but am learning ne...
8      Yes, I am not new to coding but am learning ne...
9      Yes, I am not new to coding but am learning ne...
...                                                  ...
49137  Yes, I am not new to coding but am learning ne...
49149  Yes, I am not new to coding but am learning ne...
49175  Yes, I am not new to coding but am learning ne...
49179  Yes, I am not new to coding but am learning ne...
49180  Yes, I am not new to coding but am learning ne...

                                               LearnCode  \
0      Online Courses or Certification (includes all ...
3      Other online resources (e.g. standard search, ...
7      Books / Physical media;Technical documentation...
8      Online Courses or Certification (includes all ...
9      Other online resources (e.g. standard search, ...
...                                                  ...
49137  Other online resources (e.g. standard search, ...
49149  Online Courses or Certification (includes all ...
49175  Other online resources (e.g. standard search, ...
49179  Other online resources (e.g. standard search, ...
49180  Other online resources (e.g. standard search, ...

                                             LearnCodeAI  ...  \
0      Yes, I learned how to use AI-enabled tools for...  ...
3      Yes, I learned how to use AI-enabled tools for...  ...
7      Yes, I learned how to use AI-enabled tools for...  ...
8      Yes, I learned how to use AI-enabled tools for...  ...
9      No, I learned something that was not related t...  ...
...                                                  ...  ...
49137  Yes, I learned how to use AI-enabled tools req...  ...
49149  No, I learned something that was not related t...  ...
49175  Yes, I learned how to use AI-enabled tools for...  ...
49179  No, I didn't spend time learning in the past year  ...
49180  No, I didn't spend time learning in the past year  ...

      AIAgentOrchestration  AIAgentOrchWrite  AIAgentObserveSecure  \
0                Vertex AI               NaN                   NaN
3                      NaN               NaN                   NaN
7                      NaN               NaN                   NaN
8                      NaN               NaN                   NaN
9                      NaN               NaN                   NaN
...                    ...               ...                   ...
49137                  NaN               NaN                   NaN
49149                  NaN               NaN                   NaN
49175                  NaN         llama.cpp  Grafana + Prometheus
49179                  NaN               NaN                   NaN
49180                  NaN               NaN                   NaN

      AIAgentObsWrite                    AIAgentExternal AIAgentExtWrite  \
0                 NaN                            ChatGPT             NaN
3                 NaN                ChatGPT;Claude Code             NaN
7                 NaN                                NaN             NaN
8                 NaN                                NaN             NaN
9                 NaN                                NaN             NaN
...               ...                                ...             ...
49137             NaN                                NaN             NaN
49149             NaN                                NaN             NaN
49175             NaN  ChatGPT;Claude Code;Google Gemini          Cursor
49179             NaN                                NaN             NaN
49180             NaN                                NaN             NaN

                                                 AIHuman  \
0                        When I don’t trust AI’s answers
3      When I don’t trust AI’s answers;When I want to...
7      When I want to learn best practices;When I wan...
8                                                    NaN
9      When I’m stuck and can’t explain the problem;W...
...                                                  ...
49137                            Other (please specify):
49149                                                NaN
49175  When I don’t trust AI’s answers;When I want to...
49179  When I don’t trust AI’s answers;When I want to...
49180  When I want to fully understand something;When...

                                                  AIOpen  ConvertedCompYearly  \
0                  Troubleshooting, profiling, debugging              61256.0
3                                                    NaN              36197.0
7                              Innovation, system design              72000.0
8                                                    NaN              70000.0
9                                                    NaN               5400.0
...                                                  ...                  ...
49137  Everything because this shit just doesn't work...                  NaN
49149                                                NaN                  NaN
49175                              Software Architecture                  NaN
49179                                                NaN                  NaN
49180                                                NaN                  NaN

       JobSat
0        10.0
3         6.0
7         6.0
8         8.0
9         4.0
...       ...
49137     3.0
49149     5.0
49175     8.0
49179     7.0
49180     9.0

[10931 rows x 172 columns]
Кількість респондентів, які працюють віддалено:  10931

### Завдання 5. Визначення популярності Python

In [9]:
df_data.columns[df_data.isin(['Python']).any()] #колонки з мовами програмування

Index(['TechEndorse_13_TEXT', 'TechOppose_15_TEXT', 'LanguageHaveWorkedWith',
       'LanguageWantToWorkWith', 'LanguageAdmired', 'LanguagesHaveEntry',
       'LanguagesWantEntry', 'SOTagsHaveEntry', 'SOTagsWant Entry',
       'AIAgentKnowWrite', 'AIOpen'],
      dtype='str')

In [10]:
df_python = df_data [df_data['LanguageHaveWorkedWith'].str.contains('Python', na=False)] #створення таблиці з Python-спеціалістами
df_python.to_csv('python_data.csv', index=False)

In [11]:
works_with_python = df_data['LanguageHaveWorkedWith'].str.contains('Python', na=False).sum()
python_percent = (works_with_python / responents)*100
print ('Відсоток респондентів, які програмують на Python: ', round(python_percent, 2),'%')

Відсоток респондентів, які програмують на Python:  37.54 %

### Завдання 6. Аналіз шляхів навчання програмуванню

In [12]:
cols = [c for c in df_data.columns if df_data[c].astype(str).str.contains('Online Courses', na=False).any()]
cols # стовпчики з інформацією про способи навчання

['LearnCode', 'AILearnHow']

In [13]:
print ('Кількість респондентів, які навчалися програмувати через онлайн курси: ', df_data[df_data['LearnCode'].str.contains('Online Courses', na=False)].shape[0])

Кількість респондентів, які навчалися програмувати через онлайн курси:  10973

### Завдання 7. Географічний аналіз компенсації Python-розробників

In [14]:
df_data.columns.isin(['Country']).any() #перевірка чи є колонка за назвою

np.True_

In [15]:
df_python_countries = df_python.dropna(subset=['ConvertedCompYearly'])
result = df_python.dropna(subset=['ConvertedCompYearly']).groupby('Country')[['ConvertedCompYearly']].agg(['mean', 'median'])

df_python_countries.to_csv('df_python_countries.csv', index=False)
pd.DataFrame(result).sort_values(by=('ConvertedCompYearly', 'mean'), ascending=False).round()

                         ConvertedCompYearly
                                        mean    median
Country
Oman                                390135.0  390135.0
Andorra                             226104.0  226104.0
Viet Nam                            218837.0    8254.0
United States of America            173299.0  150000.0
Switzerland                         156457.0  142592.0
...                                      ...       ...
Botswana                              1277.0    1277.0
Cambodia                              1270.0    1270.0
Togo                                   354.0     354.0
Palestine                               78.0      78.0
Antigua and Barbuda                      1.0       1.0

[153 rows x 2 columns]

### Завдання 8. Аналіз освіти найбільш оплачуваних спеціалістів

In [16]:
most_paid = df_data.dropna(subset=['ConvertedCompYearly']).sort_values(by='ConvertedCompYearly', ascending=False)[:5]
pd.DataFrame(most_paid['EdLevel'])

                                               EdLevel
34267              Associate degree (A.A., A.S., etc.)
28700  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
43143              Associate degree (A.A., A.S., etc.)
35353     Bachelor’s degree (B.A., B.S., B.Eng., etc.)
45971  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)

### Завдання 9. Аналіз популярності Python по віковим категоріям

In [17]:
result = (df_python.groupby('Age')['ResponseId'].count() / df_data.groupby('Age')['ResponseId'].count() * 100).round(2)
pd.DataFrame(result).rename(columns={"ResponseId": "Response_python_percantage, %"})

                   Response_python_percantage, %
Age
18-24 years old                            40.00
25-34 years old                            36.94
35-44 years old                            36.72
45-54 years old                            38.63
55-64 years old                            37.24
65 years or older                          31.63
Prefer not to say                          31.22

### Завдання 10. Аналіз індустрій серед високооплачуваних віддалених працівників

In [18]:
df_data.columns.isin(['Industry']).any() #перевірка чи є колонка за назвою
#df_data['Industry'].unique() #перевірка варіантів індустрії

np.True_

In [19]:
percentile_75 = df_data['ConvertedCompYearly'].quantile(0.75)
df_most_paid = df_data_remote[df_data_remote['ConvertedCompYearly']>=percentile_75]
industry_most_paid = df_most_paid['Industry'].value_counts()
pd.DataFrame(industry_most_paid)

                                            count
Industry
Software Development                         1186
Fintech                                       190
Healthcare                                    188
Other:                                        176
Internet, Telecomm or Information Services    138
Banking/Financial Services                     88
Government                                     78
Media & Advertising Services                   75
Retail and Consumer Services                   65
Transportation, or Supply Chain                63
Computer Systems Design and Services           59
Insurance                                      46
Energy                                         45
Manufacturing                                  33
Higher Education                               30